### ISSUE TITLE
基于深度卷积神经网络的图片无损放大工具

### ISSUE THREAD

**Issue by h2y** [h2y/inspirations#16]
类似于 <http://bigjpg.com>

但我想要做的是一个 Windows 应用程序，利用现有的算法思路和本地计算机强大算力。实现一个更为实用的图片放大工具。

功能包括多图片批量处理，直观的前后效果对比，算法参数动态调整等。

程序的目的是实用，而非玩具。

**Comment by h2y** [comment]
nnedi3,waifu2x,s-spline 算法在图像放大上的优缺点是什么？
<https://www.zhihu.com/question/39180891>

**Comment by h2y** [comment]
图片无损放大工具 - Benvista PhotoZoom

Benvista PhotoZoom 是一款新颖的、技术上具有革命性的对数码图片进行放大的工具。 可以对图片进行放大而没有锯齿、较少失真，包括增强的 S-Spline Max 算法、增强的图片格式支持、多处理器支持、GPU 加速、Windows 8 和 Photoshop CS6 支持等。支持作为 photoshop、Corel PHOTO-PAINT、Corel PaintShop 以及其他 Adobe 系列软件的插件运行。

**Comment by h2y** [comment]
waifu2x-caffe
已有一个 Windows 上不错的实现。

**Comment by isPoto** [comment]
> nnedi3,waifu2x,s-spline 算法在图像放大上的优缺点是什么？ https://www.zhihu.com/question/39180891

这篇文章的第一篇回答，提到的 Sony 的图像无损放大算法，你知道叫什么名字吗？是否公开？
