### ISSUE TITLE
web 文字特效单页面

### ISSUE THREAD

**Issue by h2y** [h2y/inspirations#5]
hzy.pw/word/?s=欢迎使用~！

然后进入后，用 canvas 随机绘制出 “欢迎使用” 的字样。

**Comment by h2y** [comment]
https://github.com/h2y/wordsdance
已实现，可以通过 GET 自由地设置想要显示的内容以及微调动画效果。

使用的是 CSS3 + JS，而没有使用 canvas。

**Comment by yhgao96** [comment]
haha
